version: 2
mergeable:
  - when: issues.opened
    validate:
      - do: label
        must_include:
          regex: 'Feature|Bug'
    fail:
      - do: comment
        payload:
          body: >
            The following problems were found with this issue:
              - The issue should either be labeled `Feature` or `Bug`
